-- Generated from the user-provided SQL dump. Do not edit source data manually.
-- Every statement is INSERT IGNORE, so existing managed rows are never overwritten.
INSERT IGNORE INTO `company_reviews` (`id`, `company_id`, `rating`, `content`, `createdAt`, `updatedAt`) VALUES
(1, 7, 5, 'I had an absolutely wonderful experience during the KMD recruitment process. From the moment I submitted my application, the recruitment team was incredibly responsive and communicative. The interviews felt less like an interrogation and more like a supportive, two-way conversation about my career goals. They provided great insights into the team culture, and the technical evaluation was highly relevant to the actual role. Getting hired here felt transparent and fair, and the onboarding was top-notch!', '2026-08-05 10:55:00', '2026-08-05 10:55:00'),
(2, 8, 5, 'TalentBridge Hub completely streamlined our hiring process. We posted a role and had qualified applicants within days — the platform is intuitive, and managing our job posts and candidates has never been easier. Highly recommend for any company looking to hire faster and smarter.', '2026-08-07 04:48:28', '2026-08-07 04:48:28'),
(3, 10, 4, 'Overall a strong experience using TalentBridge Hub to fill our open roles. The platform made it easy to post positions and manage applicants in one place, and we found solid candidates faster than through our usual channels. Would appreciate a few more advanced filtering options for reviewing applicants at scale, but the core hiring workflow has been reliable and efficient.', '2026-08-07 08:05:03', '2026-08-07 08:05:03'),
(4, 11, 5, 'have been using this recruitment platform for the past three months, and it has completely exceeded my expectations in every possible way. The user interface is exceptionally clean, intuitive, and highly responsive on both desktop and mobile iOS browsers. What sets this website apart from other job boards is its highly sophisticated filtering system, which allows candidates to narrow down positions by precise location, salary range, specific skill sets, and remote work flexibility. The automated email alerts are incredibly reliable and match my career goals perfectly without spamming my inbox. Uploading multiple versions of my resume and cover letter was seamless, and the internal dashboard makes tracking application statuses very straightforward. This is truly a top-tier system that bridges the gap between hiring managers and qualified candidates effectively. Five stars!', '2026-08-07 09:32:14', '2026-08-07 09:32:14');

INSERT IGNORE INTO `conversations` (`id`, `company_id`, `createdAt`, `updatedAt`) VALUES
(1, 7, '2026-08-06 07:55:04', '2026-08-06 07:55:04'),
(2, 8, '2026-08-07 06:58:40', '2026-08-07 06:58:40'),
(3, 11, '2026-08-10 06:34:17', '2026-08-10 06:34:17');

INSERT IGNORE INTO `jobs` (`id`, `title`, `company_id`, `location`, `job_type`, `salary_range`, `description`, `category_id`, `posted_at`, `createdAt`, `updatedAt`, `status`, `salary_band_id`, `application_count`, `responsibilities`, `requirements`) VALUES
(13, 'Network Engineer', 7, 'Yangon', 'Full-time', '800k', 'Need a network engineer.', 1, '2026-08-05 08:51:11', '2026-08-05 08:51:11', '2026-08-07 03:41:22', 'approved', NULL, 1, NULL, NULL),
(14, 'Customer Service', 8, 'Yangon', 'Full-time', '700k', '\"Join our growing customer support team as a Customer Service Representative! You\'ll be the first point of contact for our customers, handling inquiries via phone, email, and live chat with professionalism and care. We\'re looking for someone with excellent communication skills, a problem-solving mindset, and the patience to turn frustrated customers into loyal ones. No prior experience required — just a positive attitude and willingness to learn. In return, we offer comprehensive training, a supportive team environment, and clear paths for career growth within the company', 3, '2026-08-07 04:47:11', '2026-08-07 04:47:11', '2026-08-07 05:00:14', 'approved', NULL, 0, NULL, NULL),
(15, 'Frontend Engineer', 8, 'Yangon', 'Full-time', '700k', 'We\'re looking for a Senior Frontend Engineer to lead the development of our customer-facing web applications. You\'ll work closely with designers and backend engineers to build responsive, accessible interfaces using React and TypeScript. Requirements include 5+ years of frontend experience, strong knowledge of modern JavaScript frameworks, and experience mentoring junior developers.', 1, '2026-08-07 05:08:24', '2026-08-07 05:08:24', '2026-08-07 05:12:05', 'approved', NULL, 0, NULL, NULL),
(16, 'Marketing Coordinator', 8, 'Yangon', 'Full-time', '900k', 'Support our marketing team in planning and executing campaigns across social media, email, and content channels. Responsibilities include scheduling content, tracking campaign performance, and coordinating with designers. Ideal candidates have 1-2 years of marketing experience and strong organizational skills.', 3, '2026-08-07 05:11:59', '2026-08-07 05:11:59', '2026-08-07 05:12:04', 'approved', NULL, 0, NULL, NULL),
(17, 'Warehouse Associate', 8, 'Yangon', 'Part-time', '600k', 'Handle receiving, sorting, and shipping of inventory in a fast-paced warehouse environment. Duties include operating pallet jacks, maintaining accurate stock records, and following safety protocols. No experience necessary — training provided.', 3, '2026-08-07 06:33:37', '2026-08-07 06:33:37', '2026-08-07 06:33:46', 'approved', NULL, 0, NULL, NULL),
(18, 'Graphic Designer', 8, 'Yangon', 'Full-time', '890k', 'Create visually compelling designs for digital and print materials, including social media graphics, brochures, and branding assets. Must have a strong portfolio, proficiency in Adobe Creative Suite, and the ability to work independently on tight deadlines.', 2, '2026-08-07 06:41:28', '2026-08-07 06:41:28', '2026-08-07 06:41:47', 'approved', NULL, 0, NULL, NULL),
(19, 'Financial Analyst', 8, 'Yangon', 'Full-time', '800k', 'Analyze financial data to support business decisions, prepare forecasts, and build reporting models. Requires a bachelor\'s degree in Finance or related field, strong Excel skills, and 2+ years of experience in financial analysis or accounting.', 4, '2026-08-07 06:46:34', '2026-08-07 06:46:34', '2026-08-07 06:46:38', 'approved', NULL, 0, NULL, NULL),
(20, 'Software Engineer', 10, 'Yangon', 'Full-time', '1M', 'Join Samsung\'s mobile division to design and develop software features for our next generation of smartphones. You\'ll work on performance optimization, OS-level integrations, and collaborate with global hardware teams. Requires a strong background in Java/Kotlin or C++, experience with Android internals, and a degree in Computer Science or related field.', 5, '2026-08-07 07:08:20', '2026-08-07 07:08:20', '2026-08-07 07:08:25', 'approved', NULL, 0, NULL, NULL),
(21, 'Product Marketing Manager', 10, 'Yangon', 'Full-time', '2M', 'Lead go-to-market strategy for a portfolio of Samsung consumer electronics products. Responsibilities include market research, competitive analysis, campaign planning, and coordinating cross-functional launches with sales and design teams. Requires 4+ years of product marketing experience, ideally in consumer tech.', 3, '2026-08-07 07:09:18', '2026-08-07 07:09:18', '2026-08-07 07:09:22', 'approved', NULL, 0, NULL, NULL),
(22, 'Supply Chain Analyst', 10, 'Mandalay', 'Full-time', '800k', 'Support demand planning and inventory optimization across Samsung\'s semiconductor and electronics supply chain. Analyze forecasting data, identify process improvements, and collaborate with manufacturing and logistics partners. Requires strong analytical skills and proficiency in Excel/SQL; supply chain experience preferred.', 1, '2026-08-07 07:10:10', '2026-08-07 07:10:10', '2026-08-07 07:10:19', 'approved', NULL, 0, NULL, NULL),
(23, 'UI/UX Designer', 10, 'Naypyidaw', 'Full-time', '800k', 'Design intuitive, visually engaging interfaces for Samsung\'s mobile and smart device ecosystem. Collaborate with product managers and engineers to translate user needs into polished experiences, from wireframes to high-fidelity prototypes. Requires a strong portfolio, proficiency in Figma, and 3+ years of UX/UI design experience.', 2, '2026-08-07 07:11:15', '2026-08-07 07:11:15', '2026-08-07 07:11:19', 'approved', NULL, 0, NULL, NULL),
(24, 'Web Developer', 9, 'Remote', 'Full-time', '900k', 'Tech Khit Au is looking for a Web Developer to join our growing team building and maintaining digital solutions for clients across various industries. You\'ll work on responsive websites, custom web applications, and integrations, collaborating closely with our design and project teams. Requirements include solid experience with HTML, CSS, JavaScript, and at least one modern framework (React, Vue, or similar), plus strong communication skills for client-facing work.', 1, '2026-08-07 08:59:46', '2026-08-07 08:59:46', '2026-08-07 08:59:52', 'approved', NULL, 0, '[\"Build and maintain responsive websites and custom web applications for clients across various industries\",\"Collaborate with designers to translate mockups into functional, pixel-accurate interfaces\",\"Integrate third-party APIs and services as needed for client projects\",\"Troubleshoot and fix bugs across existing client websites\",\"Participate in code reviews and follow team coding standards\"]', '[\"Solid experience with HTML, CSS, and JavaScript\",\"Proficiency in at least one modern framework (React, Vue, or similar)\",\"Understanding of responsive design and cross-browser compatibility\",\"Strong communication skills for client-facing work\",\"Prior freelance or agency experience is a plus\"]'),
(25, 'Digital Project Manager', 9, 'Remote', 'Full-time', '1M', 'Manage the delivery of web and digital projects from kickoff to launch, coordinating between clients, designers, and developers. Responsibilities include timeline management, client communication, and ensuring projects stay on budget and scope. Requires 3+ years of experience managing digital/web projects, strong organizational skills, and familiarity with agile workflows.', 3, '2026-08-07 09:26:55', '2026-08-07 09:26:55', '2026-08-07 09:27:36', 'approved', NULL, 0, '[\"Manage web and digital projects from kickoff through delivery\",\"Act as the primary point of contact between clients, designers, and developers\",\"Create and maintain project timelines, ensuring deadlines and budgets are met\",\"Facilitate stand-ups, sprint planning, and other agile ceremonies\",\"Identify and resolve project risks or scope changes early\"]', '[\"3+ years of experience managing digital or web projects\",\"Strong organizational and time-management skills\",\"Familiarity with agile/scrum workflows and tools (Jira, Trello, or similar)\",\"Excellent written and verbal communication skills\",\"Ability to manage multiple client projects simultaneously\"]'),
(26, 'iOS Software Engineer', 11, 'Yangon', 'Full-time', '13M', 'Apple is seeking an iOS Software Engineer to join our team building software experiences used by millions of people around the world. You\'ll work on core features across our iOS app ecosystem, partnering closely with design and product teams to ship intuitive, high-performance experiences that meet Apple\'s exacting quality standards. This role offers the opportunity to work on challenging technical problems at massive scale while collaborating with some of the best engineers in the industry.', 1, '2026-08-10 06:39:57', '2026-08-10 06:39:57', '2026-08-10 06:40:03', 'approved', NULL, 0, '[\"Design and develop new features for Apple\'s iOS applications and frameworks\",\"Collaborate with design, product, and QA teams to deliver polished, reliable software\",\"Write clean, well-tested Swift code and participate in code reviews\",\"Optimize app performance, memory usage, and battery efficiency\",\"Debug and resolve issues reported through internal testing and user feedback\"]', '[\"Strong proficiency in Swift and experience with iOS SDKs (UIKit/SwiftUI)\",\"Solid understanding of mobile app architecture and design patterns\",\"Experience with version control (Git) and collaborative development workflows\",\"Bachelor\'s degree in Computer Science or equivalent practical experience\",\"Excellent problem-solving skills and attention to detail\"]'),
(27, 'Hardware Engineer', 11, 'Yangon', 'Full-time', '12M', 'Apple is looking for a Hardware Engineer to join our device engineering team, working on the design and validation of next-generation consumer electronics. You\'ll collaborate closely with mechanical, electrical, and manufacturing teams to bring products from prototype to mass production, all while upholding Apple\'s high standards for quality and precision.', 5, '2026-08-10 07:41:19', '2026-08-10 07:41:19', '2026-08-10 07:44:09', 'approved', NULL, 0, '[\"Design, test, and validate hardware components for upcoming Apple products\",\"Work cross-functionally with mechanical and electrical engineering teams\",\"Analyze test data and troubleshoot hardware issues during development\",\"Support manufacturing teams through the production ramp process\",\"Document design specifications and maintain engineering change records\"]', '[\"Bachelor\'s or Master\'s degree in Electrical, Mechanical, or Computer Engineering\",\"Experience with hardware design tools (CAD, schematic capture, simulation software)\",\"Understanding of PCB design and hardware validation processes\",\"Strong analytical and problem-solving skills\",\"Prior experience in consumer electronics product development is a plus\"]'),
(28, 'Retail Store Manager', 11, 'Yangon', 'Full-time', '10M', 'Lead an Apple Store team in delivering exceptional customer experiences. As Store Manager, you\'ll oversee daily operations, coach and develop your team, and ensure the store consistently reflects Apple\'s brand and service standards. This role combines people leadership with a passion for helping customers discover what Apple products can do for them.', 3, '2026-08-10 07:43:57', '2026-08-10 07:43:57', '2026-08-10 07:44:08', 'approved', NULL, 0, '[\"Manage day-to-day store operations, staffing, and scheduling\",\"Coach, mentor, and develop retail team members\",\"Ensure store visual merchandising aligns with Apple\'s brand guidelines\",\"Monitor sales performance and implement strategies to meet targets\",\"Handle escalated customer service issues with professionalism\"]', '[\"3+ years of retail management experience, preferably in tech or consumer electronics\",\"Strong leadership and team development skills\",\"Excellent communication and customer service abilities\",\"Ability to work flexible hours including weekends and holidays\",\"Passion for Apple products and technology\"]');

INSERT IGNORE INTO `job_seeker_reviews` (`id`, `job_seeker_id`, `rating`, `content`, `createdAt`, `updatedAt`) VALUES
(1, 5, 5, 'I was job hunting for months with no luck until I found TalentBridge Hub. Applied to a Marketing Coordinator role and got hired within two weeks. The application process was so simple, and I loved being able to track my application status the whole way through.', '2026-08-07 08:03:42', '2026-08-07 08:03:42');

INSERT IGNORE INTO `messages` (`id`, `conversation_id`, `sender`, `body`, `read`, `createdAt`) VALUES
(1, 1, 'admin', 'hi', 'read', '2026-08-06 07:55:08'),
(2, 1, 'company', 'hi', 'read', '2026-08-07 03:56:05'),
(3, 3, 'admin', 'Hello this is from the Daniel D Harrington, the founder and ceo of the TBH. We are so glad that you guys joined to our job recruitment website.', 'read', '2026-08-10 06:35:24'),
(4, 3, 'admin', 'Hope all your positions found with the best employees.', 'read', '2026-08-10 06:35:58'),
(5, 3, 'company', 'Thank you for the wish and we really appreciate you for all the process in this website.', 'read', '2026-08-10 06:37:05');

INSERT IGNORE INTO `notifications` (`id`, `recipientRole`, `recipient_id`, `title`, `content`, `type`, `is_read`, `createdAt`) VALUES
(1, 'admin', NULL, 'Password reset requested', 'Jinny (jinny@gmail.com) has forgotten their password and requested a reset. Please log in to the admin portal → Job Seekers and reset their password.', 'password_reset', 'read', '2026-08-10 04:00:32'),
(2, 'admin', NULL, 'Company password reset requested', 'KMD College (kmd@gmail.com) has forgotten their company password and requested a reset. Please log in to the admin portal -> Notifications and reset their password.', 'password_reset', 'read', '2026-08-10 06:33:35');
